name: miniarch
description: Minimal Flutter Architecture Setup
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  

  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_gen: any  
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.3
  fluttertoast: ^8.2.5
  freezed: 
  freezed_annotation: ^2.4.1
  go_router: ^14.2.6
  reactive_forms: ^17.0.1
  responsive_framework: ^1.4.0
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner:
  custom_lint:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
